// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW4iiHofDF3wwDTsE60dULyv4fmMSBkUg',
    appId: '1:598984552614:web:b070555028cc65b8570467',
    messagingSenderId: '598984552614',
    projectId: 'birds-and-friends-v2',
    authDomain: 'birds-and-friends-v2.firebaseapp.com',
    storageBucket: 'birds-and-friends-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIruO7COib99FcouVbDSRBo1vhMpI84P0',
    appId: '1:598984552614:android:b43e770afbe71b2b570467',
    messagingSenderId: '598984552614',
    projectId: 'birds-and-friends-v2',
    storageBucket: 'birds-and-friends-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVeUGiRV-wJLmsByN47GCUQZWmTTk4LE',
    appId: '1:598984552614:ios:f67f5fea362680f0570467',
    messagingSenderId: '598984552614',
    projectId: 'birds-and-friends-v2',
    storageBucket: 'birds-and-friends-v2.firebasestorage.app',
    iosBundleId: 'de.lukasgerhardt.birdsAndFriends',
  );

}